/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <USBFS.h>
#include <USBFS_audio.h>
#include <USBFS_cdc.h>
#include <USBFS_hid.h>
#include <USBFS_midi.h>
#include <ADC.h>
#include <SW_In_aliases.h>
#include <SW_In.h>
#include <LED_1_aliases.h>
#include <LED_1.h>
#include <PWM.h>
#include <PWM_Clock.h>
#include <LED_2_aliases.h>
#include <LED_2.h>
#include <Finger1_aliases.h>
#include <Finger1.h>
#include <LCD.h>
#include <Finger4_aliases.h>
#include <Finger4.h>
#include <Finger3_aliases.h>
#include <Finger3.h>
#include <Finger2_aliases.h>
#include <Finger2.h>
#include <AMux_1.h>
#include <USBFS_Dm_aliases.h>
#include <USBFS_Dp_aliases.h>
#include <USBFS_Dp.h>
#include <ADC_theACLK.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_AMux.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

